#[derive(Debug, PartialEq)]
pub enum Token<'a> {
    Error(String),
    EndOfCode,
    EndOfLine,
    OpenParen,
    CloseParen,
    OpenCurly,
    CloseCurly,
    Or,
    And,
    Equal,
    NotEqual,
    LessThan,
    LessThanOrEqual,
    GreaterThanOrEqual,
    GreaterThan,
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    ShiftLeft,
    ShiftRight,
    BitwiseOr,
    BitwiseXor,
    BitwiseAnd,
    Function,
    False,
    True,
    IntLiteral(i64),
    Identifier(&'a str),
}
